import logging
from typing import Any, Dict, List, Optional
import httpx
from config.settings import Settings

logger = logging.getLogger(__name__)

class TavilySearch:
    """
    A client wrapper for the Tavily Search API.
    """
    API_URL = "https://api.tavily.com/search"

    def __init__(self, api_key: Optional[str] = None):
        """
        Initialize the Tavily search client.
        
        Args:
            api_key: The Tavily API key. If not provided, it will be loaded from settings.
        """
        self.api_key = api_key or Settings.tavily_api_key
        if not self.api_key:
            logger.warning("Tavily API key is not configured. Search queries will fail.")

    def search(
        self,
        query: str,
        search_depth: str = "basic",
        max_results: int = 5,
        include_answer: bool = False,
        include_raw_content: bool = False,
        include_images: bool = False,
        include_domains: Optional[List[str]] = None,
        exclude_domains: Optional[List[str]] = None,
        **kwargs: Any
    ) -> Dict[str, Any]:
        """
        Perform a synchronous web search using Tavily API.
        
        Args:
            query: The search query.
            search_depth: "basic" or "advanced".
            max_results: The maximum number of search results to return.
            include_answer: Whether to include a short answer generated by Tavily.
            include_raw_content: Whether to include the raw HTML content of the page.
            include_images: Whether to include images in the results.
            include_domains: List of domains to include in the search.
            exclude_domains: List of domains to exclude from the search.
            **kwargs: Extra parameters to pass to the Tavily API.
            
        Returns:
            A dictionary containing the search response.
        """
        if not self.api_key:
            raise ValueError("Tavily API key must be configured to perform a search.")

        payload = {
            "api_key": self.api_key,
            "query": query,
            "search_depth": search_depth,
            "max_results": max_results,
            "include_answer": include_answer,
            "include_raw_content": include_raw_content,
            "include_images": include_images,
        }

        if include_domains:
            payload["include_domains"] = include_domains
        if exclude_domains:
            payload["exclude_domains"] = exclude_domains

        payload.update(kwargs)

        try:
            with httpx.Client(timeout=30.0) as client:
                response = client.post(self.API_URL, json=payload)
                response.raise_for_status()
                json_data = response.json()
                cleaned_data = {
                    "claim": query,
                    "evidence": [
                        {
                            "url": item["url"],
                            "title": item["title"],
                            "content": item["content"],
                            "relevance_score": item["score"],
                        }
                        for item in json_data["results"]
                    ]
                }
                return cleaned_data
        except httpx.HTTPStatusError as e:
            logger.error(f"Tavily API HTTP error: {e.response.status_code} - {e.response.text}")
            raise
        except Exception as e:
            logger.error(f"Error communicating with Tavily API: {e}")
            raise

    async def search_async(
        self,
        query: str,
        search_depth: str = "basic",
        max_results: int = 5,
        include_answer: bool = False,
        include_raw_content: bool = False,
        include_images: bool = False,
        include_domains: Optional[List[str]] = None,
        exclude_domains: Optional[List[str]] = None,
        **kwargs: Any
    ) -> Dict[str, Any]:
        """
        Perform an asynchronous web search using Tavily API.
        
        Args:
            query: The search query.
            search_depth: "basic" or "advanced".
            max_results: The maximum number of search results to return.
            include_answer: Whether to include a short answer generated by Tavily.
            include_raw_content: Whether to include the raw HTML content of the page.
            include_images: Whether to include images in the results.
            include_domains: List of domains to include in the search.
            exclude_domains: List of domains to exclude from the search.
            **kwargs: Extra parameters to pass to the Tavily API.
            
        Returns:
            A dictionary containing the search response.
        """
        if not self.api_key:
            raise ValueError("Tavily API key must be configured to perform a search.")

        payload = {
            "api_key": self.api_key,
            "query": query,
            "search_depth": search_depth,
            "max_results": max_results,
            "include_answer": include_answer,
            "include_raw_content": include_raw_content,
            "include_images": include_images,
        }

        if include_domains:
            payload["include_domains"] = include_domains
        if exclude_domains:
            payload["exclude_domains"] = exclude_domains

        payload.update(kwargs)

        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                response = await client.post(self.API_URL, json=payload)
                response.raise_for_status()
                json_data = response.json()
                cleaned_data = {
                    "claim": query,
                    "evidence": [
                        {
                            "url": item["url"],
                            "title": item["title"],
                            "content": item["content"],
                            "relevance_score": item["score"],
                        }
                        for item in json_data["results"]
                    ]
                }
                return cleaned_data
        except httpx.HTTPStatusError as e:
            logger.error(f"Tavily API async HTTP error: {e.response.status_code} - {e.response.text}")
            raise
        except Exception as e:
            logger.error(f"Error communicating asynchronously with Tavily API: {e}")
            raise


if __name__ == "__main__":
    searcher = TavilySearch()
    results = searcher.search("Red meat cause cancer?", include_domains=["pubmed.ncbi.nlm.nih.gov", "cochranelibrary.com"], max_results=3)
    print(results)
